/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char* _oda_int_to_str(int v) {
    char* buf = (char*)malloc(24);
    snprintf(buf, 24, "%d", v);
    return buf;
}

static char* _oda_float_to_str(double v) {
    char* buf = (char*)malloc(48);
    snprintf(buf, 48, "%g", v);
    return buf;
}

static char* _oda_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* r = (char*)malloc(la + lb + 1);
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}

static char* _oda_input() {
    char* buf = (char*)malloc(1024);
    if (fgets(buf, 1024, stdin) != NULL) {
        size_t len = strlen(buf);
        if (len > 0 && buf[len-1] == '\n') buf[len-1] = '\0';
    }
    return buf;
}

static char* _oda_read_file(const char* path) {
    FILE* f = fopen(path, "r");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* string = (char*)malloc(fsize + 1);
    fread(string, fsize, 1, f);
    fclose(f);
    string[fsize] = 0;
    return string;
}



int main(void) {
    int static_arr[3] = {1, 2, 3};
    int* dynamic_arr = (int[]){4, 5, 6};
    printf("%s\n", _oda_str_concat("Static arr[0]: ", _oda_int_to_str(static_arr[0])));
    printf("%s\n", _oda_str_concat("Dynamic arr[1]: ", _oda_int_to_str(dynamic_arr[1])));
    static_arr[0] = 100;
    dynamic_arr[1] = 500;
    printf("After mutation:\n");
    printf("%s\n", _oda_str_concat("Static arr[0]: ", _oda_int_to_str(static_arr[0])));
    printf("%s\n", _oda_str_concat("Dynamic arr[1]: ", _oda_int_to_str(dynamic_arr[1])));
    printf("Please enter something:\n");
    char* user_input = _oda_input();
    printf("%s\n", _oda_str_concat("You entered: ", user_input));
    return 0;
}
