"""C code generator — translates the OdaLanguage AST into a Unity Build C file."""
from __future__ import annotations
from . import ast_nodes as ast

# C type mapping
_C_TYPES = {
    "int": "int", "uint": "unsigned int", "float": "double",
    "char": "char", "string": "char*", "bool": "int",
}

_FMT = {
    "int": "%d", "uint": "%u", "float": "%f",
    "char": "%c", "string": "%s", "bool": "%d",
}

_ERROR_CONSTANTS = {
    "FileNotFound": "ODA_ERROR_FILE_NOT_FOUND",
    "PermissionDenied": "ODA_ERROR_PERMISSION_DENIED",
    "IoError": "ODA_ERROR_IO",
}


class CCodeGenerator:
    def __init__(self):
        self.indent = 0
        self._top: list[str] = []        # structs, prototypes
        self._funcs: list[str] = []      # function definitions
        self._main: list[str] = []       # top-level → main()
        self._helpers_emitted: set[str] = set()
        self._class_names: set[str] = set()
        self._enum_variants: dict[str, set[str]] = {}
        self._destructors: list[tuple[str, str]] = []  # (class, varname)
        self._scope_starts: list[int] = []
        self._func_starts: list[int] = []
        self._heap_vars: list[str] = []
        self._heap_starts: list[int] = []
        self._func_heap_starts: list[int] = []
        self._temp_counter = 0
        self._var_types: dict[str, str] = {}  # variable name → oda type
        self._var_sizes: dict[str, list[int]] = {}  # dimensions for arrays
        self._func_params: dict[str, list[ast.Parameter]] = {}  # func name → param list
        self._func_return_types: dict[str, str] = {}  # func name → return oda type
        self._ref_params: set[str] = set()  # currently active ref param names
        self._expr_preludes: list[list[str]] = []

    # ── public API ───────────────────────────────────────────
    def generate(self, program: ast.Program) -> str:
        # Discover classes and functions first
        for s in program.statements:
            if isinstance(s, ast.ClassDeclaration):
                self._class_names.add(s.name)
                if s.constructor:
                    self._func_params[f"{s.name}_construct"] = [ast.Parameter(type_ann=ast.TypeAnnotation(base_type=s.name), name="self", is_ref=True)] + s.constructor.params
                for m in s.methods:
                    self._func_params[f"{s.name}_{m.name}"] = [ast.Parameter(type_ann=ast.TypeAnnotation(base_type=s.name), name="self", is_ref=True)] + m.params
            elif isinstance(s, ast.EnumDeclaration):
                self._enum_variants[s.name] = set(s.variants)
            elif isinstance(s, ast.FuncDeclaration):
                self._func_params[s.name] = s.params
                if s.return_type:
                    self._func_return_types[s.name] = s.return_type.base_type

        for s in program.statements:
            self._emit_toplevel(s)

        return self._assemble()

    # ── assembly ─────────────────────────────────────────────
    def _assemble(self) -> str:
        lines = [
            "/* Generated by OdaLanguage Transpiler v0.1 */",
            "#include <errno.h>",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "",
            "#if defined(__GNUC__) || defined(__clang__)",
            "#define ODA_UNUSED __attribute__((unused))",
            "#else",
            "#define ODA_UNUSED",
            "#endif",
            "",
            "#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L",
            "#define ODA_THREAD_LOCAL _Thread_local",
            "#else",
            "#define ODA_THREAD_LOCAL",
            "#endif",
            "",
            "typedef enum {",
            "    ODA_ERROR_NONE = 0,",
            "    ODA_ERROR_FILE_NOT_FOUND,",
            "    ODA_ERROR_PERMISSION_DENIED,",
            "    ODA_ERROR_IO",
            "} OdaError;",
            "",
            "static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;",
            "",
        ]
        if "_oda_str_concat" not in self._helpers_emitted:
            self._emit_str_helper()
        lines += self._top
        lines.append("")
        lines += self._funcs
        lines.append("")
        lines.append("int main(void) {")
        lines += ["    " + l for l in self._main]
        # RAII: inject destructors
        for class_name, var_name in reversed(self._destructors):
            lines.append(f"    {class_name}_destruct(&{var_name});")
        while self._heap_vars:
            lines.append(f"    free({self._heap_vars.pop()});")
        lines.append("    return 0;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_str_helper(self):
        self._helpers_emitted.add("_oda_str_concat")
        self._top += [
            "static ODA_UNUSED char* _oda_int_to_str(int v) {",
            "    char* buf = (char*)malloc(24);",
            "    snprintf(buf, 24, \"%d\", v);",
            "    return buf;",
            "}",
            "",
            "static ODA_UNUSED char* _oda_float_to_str(double v) {",
            "    char* buf = (char*)malloc(48);",
            "    snprintf(buf, 48, \"%g\", v);",
            "    return buf;",
            "}",
            "",
            "static ODA_UNUSED char* _oda_str_concat(const char* a, const char* b) {",
            "    size_t la = strlen(a), lb = strlen(b);",
            "    char* r = (char*)malloc(la + lb + 1);",
            "    memcpy(r, a, la);",
            "    memcpy(r + la, b, lb + 1);",
            "    return r;",
            "}",
            "",
            "static ODA_UNUSED char* _oda_input() {",
            "    size_t cap = 64;",
            "    size_t len = 0;",
            "    char* buf = (char*)malloc(cap);",
            "    if (!buf) {",
            "        fprintf(stderr, \"oda: input allocation failed\\n\");",
            "        exit(1);",
            "    }",
            "    int ch;",
            "    while ((ch = fgetc(stdin)) != EOF && ch != '\\n') {",
            "        if (len + 1 >= cap) {",
            "            size_t new_cap = cap * 2;",
            "            char* new_buf = (char*)realloc(buf, new_cap);",
            "            if (!new_buf) {",
            "                free(buf);",
            "                fprintf(stderr, \"oda: input allocation failed\\n\");",
            "                exit(1);",
            "            }",
            "            buf = new_buf;",
            "            cap = new_cap;",
            "        }",
            "        buf[len++] = (char)ch;",
            "    }",
            "    buf[len] = '\\0';",
            "    return buf;",
            "}",
            "",
            "static ODA_UNUSED char* _oda_read_file(const char* path) {",
            "    errno = 0;",
            "    FILE* f = fopen(path, \"r\");",
            "    if (!f) {",
            "        if (errno == ENOENT || errno == ENOTDIR) {",
            "            _oda_error = ODA_ERROR_FILE_NOT_FOUND;",
            "        } else if (errno == EACCES || errno == EPERM) {",
            "            _oda_error = ODA_ERROR_PERMISSION_DENIED;",
            "        } else {",
            "            _oda_error = ODA_ERROR_IO;",
            "        }",
            "        return NULL;",
            "    }",
            "    fseek(f, 0, SEEK_END);",
            "    long fsize = ftell(f);",
            "    fseek(f, 0, SEEK_SET);",
            "    char* string = (char*)malloc(fsize + 1);",
            "    if (!string) {",
            "        fclose(f);",
            "        _oda_error = ODA_ERROR_IO;",
            "        return NULL;",
            "    }",
            "    fread(string, fsize, 1, f);",
            "    fclose(f);",
            "    string[fsize] = 0;",
            "    _oda_error = ODA_ERROR_NONE;",
            "    return string;",
            "}",
            "",
        ]

    def _emit_alloc_helper(self, depth: int):
        """Recursively generate _oda_alloc_Nd helpers if needed."""
        if depth < 2: return
        func_name = f"_oda_alloc_{depth}d"
        if func_name in self._helpers_emitted: return
        
        # Ensure dependencies (e.g. 2d for 3d) are emitted first
        if depth > 2:
            self._emit_alloc_helper(depth - 1)
            
        self._helpers_emitted.add(func_name)
        
        args = ", ".join(f"int d{i+1}" for i in range(depth))
        stars_ret = "*" * depth
        stars_inner = "*" * (depth - 1)
        
        lines = [
            f"static void{stars_ret} {func_name}({args}, size_t size) {{",
            f"    void{stars_ret} arr = (void{stars_ret})malloc(d1 * sizeof(void{stars_inner}));",
            "    for(int i = 0; i < d1; i++) {"
        ]
        
        if depth == 2:
            lines.append("        arr[i] = (void*)malloc(d2 * size);")
        else:
            inner_args = ", ".join(f"d{i+1}" for i in range(1, depth))
            lines.append(f"        arr[i] = (void{stars_inner})_oda_alloc_{depth-1}d({inner_args}, size);")
            
        lines.append("    }")
        lines.append("    return arr;")
        lines.append("}")
        lines.append("")
        
        self._top += lines

    def _next_temp(self) -> str:
        self._temp_counter += 1
        return f"_oda_tmp_{self._temp_counter}"

    def _capture_expr(self, node, class_ctx=None, *, owns_result: bool = False) -> tuple[list[str], str]:
        self._expr_preludes.append([])
        expr = self._expr(node, class_ctx, owns_result=owns_result)
        return self._expr_preludes.pop(), expr

    def _capture_code(self, fn) -> tuple[list[str], str]:
        self._expr_preludes.append([])
        code = fn()
        return self._expr_preludes.pop(), code

    def _add_expr_prelude(self, line: str):
        if self._expr_preludes:
            self._expr_preludes[-1].append(line)

    def _track_heap_temp(self, c_type: str, expr_code: str) -> str:
        if not self._expr_preludes:
            return expr_code
        tmp = self._next_temp()
        self._add_expr_prelude(f"{c_type} {tmp} = {expr_code};")
        self._heap_vars.append(tmp)
        return tmp

    # ── top-level dispatch ───────────────────────────────────
    def _emit_toplevel(self, stmt):
        if isinstance(stmt, ast.ClassDeclaration):
            self._emit_class(stmt)
        elif isinstance(stmt, ast.EnumDeclaration):
            self._emit_enum(stmt)
        elif isinstance(stmt, ast.FuncDeclaration):
            self._emit_func_def(stmt)
        elif isinstance(stmt, ast.ImportStatement):
            self._top.append(f"/* import {stmt.module_path} */")
        else:
            # Top-level code goes into main()
            self._emit_stmt(stmt, self._main)

    # ── class → struct + functions ───────────────────────────
    def _emit_enum(self, enum: ast.EnumDeclaration):
        self._top.append("typedef enum {")
        for i, variant in enumerate(enum.variants):
            comma = "," if i < len(enum.variants) - 1 else ""
            self._top.append(f"    {enum.name}_{variant}{comma}")
        self._top.append(f"}} {enum.name};")
        self._top.append("")

    def _emit_class(self, cls: ast.ClassDeclaration):
        self._top.append(f"typedef struct {{")
        for f in cls.fields:
            ct = self._c_type(f.type_ann)
            self._top.append(f"    {ct} {f.name};")
        self._top.append(f"}} {cls.name};")
        self._top.append("")

        # Constructor
        if cls.constructor:
            params = ", ".join(
                [self._param_c(p) for p in cls.constructor.params]
            )
            self._funcs.append(f"void {cls.name}_construct({cls.name}* self{', ' + params if params else ''}) {{")
            body_lines: list[str] = []
            old_refs = self._ref_params
            self._ref_params = {p.name for p in cls.constructor.params if p.is_ref}
            self._func_starts.append(len(self._destructors))
            self._func_heap_starts.append(len(self._heap_vars))
            self._emit_block(cls.constructor.body, body_lines, cls.name)
            self._func_heap_starts.pop()
            self._func_starts.pop()
            self._ref_params = old_refs
            self._funcs += ["    " + l for l in body_lines]
            self._funcs.append("}")
            self._funcs.append("")

        # Methods
        for m in cls.methods:
            params = ", ".join(
                [self._param_c(p) for p in m.params]
            )
            ret = "void"
            if m.return_type:
                ret = self._c_type(m.return_type)
            self._funcs.append(f"{ret} {cls.name}_{m.name}({cls.name}* self{', ' + params if params else ''}) {{")
            body_lines = []
            old_refs = self._ref_params
            self._ref_params = {p.name for p in m.params if p.is_ref}
            self._func_starts.append(len(self._destructors))
            self._func_heap_starts.append(len(self._heap_vars))
            self._emit_block(m.body, body_lines, cls.name)
            self._func_heap_starts.pop()
            self._func_starts.pop()
            self._ref_params = old_refs
            self._funcs += ["    " + l for l in body_lines]
            self._funcs.append("}")
            self._funcs.append("")

        # Destructor
        if cls.destructor:
            self._funcs.append(f"void {cls.name}_destruct({cls.name}* self) {{")
            body_lines = []
            self._func_heap_starts.append(len(self._heap_vars))
            self._emit_block(cls.destructor.body, body_lines, cls.name)
            self._func_heap_starts.pop()
            self._funcs += ["    " + l for l in body_lines]
            self._funcs.append("}")
            self._funcs.append("")

    # ── function definition ──────────────────────────────────
    def _emit_func_def(self, func: ast.FuncDeclaration):
        self._func_params[func.name] = func.params
        if func.return_type:
            self._func_return_types[func.name] = func.return_type.base_type
        params = ", ".join(self._param_c(p) for p in func.params)
        if not params:
            params = "void"
        ret = "void"
        if func.return_type:
            ret = self._c_type(func.return_type)
        self._funcs.append(f"{ret} {func.name}({params}) {{")
        # Only ref-marked parameters become pointers
        old_refs = self._ref_params
        self._ref_params = {p.name for p in func.params if p.is_ref}
        for p in func.params:
            self._var_types[p.name] = p.type_ann.base_type
        body_lines: list[str] = []
        self._func_starts.append(len(self._destructors))
        self._func_heap_starts.append(len(self._heap_vars))
        self._emit_block(func.body, body_lines)
        self._func_heap_starts.pop()
        self._func_starts.pop()
        self._funcs += ["    " + l for l in body_lines]
        self._funcs.append("}")
        self._funcs.append("")
        self._ref_params = old_refs

    # ── statements ───────────────────────────────────────────
    def _emit_stmt(self, stmt, out: list[str], class_ctx: str | None = None):
        if isinstance(stmt, ast.VarDeclaration):
            self._emit_var_decl(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ExpressionStatement):
            self._emit_expr_stmt(stmt, out, class_ctx)
        elif isinstance(stmt, ast.IfStatement):
            self._emit_if(stmt, out, class_ctx)
        elif isinstance(stmt, ast.WhileStatement):
            self._emit_while(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ForStatement):
            self._emit_for(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ForRangeStatement):
            self._emit_for_range(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ForInStatement):
            self._emit_for_in(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ReturnStatement):
            prelude = []
            value = None
            if stmt.value:
                prelude, value = self._capture_expr(
                    stmt.value,
                    class_ctx,
                    owns_result=self._expr_allocates_heap(stmt.value),
                )
                out += prelude
            if self._func_starts:
                start = self._func_starts[-1]
                for i in range(len(self._destructors) - 1, start - 1, -1):
                    cn, vn = self._destructors[i]
                    out.append(f"{cn}_destruct(&{vn});")
            if self._func_heap_starts:
                self._emit_heap_cleanup_from(out, self._func_heap_starts[-1], pop=False)
            if stmt.value:
                out.append(f"return {value};")
            else:
                out.append("return;")
        elif isinstance(stmt, ast.BreakStatement):
            out.append("break;")
        elif isinstance(stmt, ast.ContinueStatement):
            out.append("continue;")
        elif isinstance(stmt, ast.MatchStatement):
            self._emit_match(stmt, out, class_ctx)
        elif isinstance(stmt, ast.GuardStatement):
            self._emit_guard(stmt, out, class_ctx)

    def _emit_block(self, stmts: list, out: list[str], class_ctx: str | None = None):
        self._scope_starts.append(len(self._destructors))
        self._heap_starts.append(len(self._heap_vars))
        for s in stmts:
            self._emit_stmt(s, out, class_ctx)
        
        # Block exit RAII
        exits_with_return = bool(stmts) and isinstance(stmts[-1], ast.ReturnStatement)
        start = self._scope_starts.pop()
        while len(self._destructors) > start:
            cn, vn = self._destructors.pop()
            if not exits_with_return:
                out.append(f"{cn}_destruct(&{vn});")
        heap_start = self._heap_starts.pop()
        if exits_with_return:
            while len(self._heap_vars) > heap_start:
                self._heap_vars.pop()
        else:
            self._emit_heap_cleanup_from(out, heap_start, pop=True)

    def _emit_heap_cleanup_from(self, out: list[str], start: int, *, pop: bool):
        if pop:
            while len(self._heap_vars) > start:
                out.append(f"free({self._heap_vars.pop()});")
            return

        for var_name in reversed(self._heap_vars[start:]):
            out.append(f"free({var_name});")

    def _expr_allocates_heap(self, node) -> bool:
        if isinstance(node, ast.CastExpr):
            return self._expr_allocates_heap(node.expr)
        if isinstance(node, ast.ArrayAllocation):
            return True
        if isinstance(node, ast.InterpolatedString):
            return True
        if isinstance(node, ast.BinaryExpr):
            return node.op == "+" and self._looks_like_string(node)
        if isinstance(node, ast.CallExpr) and isinstance(node.callee, ast.Identifier):
            return node.callee.name in ("input", "readFile")
        return False

    def _heap_expr_c_type(self, node) -> str:
        if isinstance(node, ast.ArrayAllocation):
            base = _C_TYPES.get(node.base_type, node.base_type)
            return f"{base}{'*' * len(node.sizes)}"
        return "char*"

    def _materialize_heap_expr(self, node, expr_code: str, *, owns_result: bool) -> str:
        if owns_result:
            return expr_code
        return self._track_heap_temp(self._heap_expr_c_type(node), expr_code)

    def _emit_array_expr(self, node, ta: ast.TypeAnnotation, class_ctx=None) -> str:
        if isinstance(node, ast.ArrayLiteral):
            base = _C_TYPES.get(ta.base_type, ta.base_type)
            depth = ta.array_depth
            elems = []
            for e in node.elements:
                if isinstance(e, ast.ArrayLiteral):
                    # nested
                    inner_ta = ast.TypeAnnotation(base_type=ta.base_type, is_array=True, array_depth=depth-1)
                    elems.append(self._emit_array_expr(e, inner_ta, class_ctx))
                else:
                    elems.append(self._expr(e, class_ctx))
            
            stars = "*" * (depth - 1)
            cast = f"({base}{stars}[])" if depth > 0 else ""
            return f"{cast}{{{', '.join(elems)}}}"
        return self._expr(node, class_ctx)

    def _emit_var_decl(self, v: ast.VarDeclaration, out: list[str], class_ctx=None):
        ct = self._c_type(v.type_ann)
        prefix = "const " if v.is_immutable else ""
        base_c = _C_TYPES.get(v.type_ann.base_type, v.type_ann.base_type)

        if v.type_ann.is_array:
            dims = []
            def get_dims(expr):
                if isinstance(expr, ast.ArrayLiteral):
                    d = [len(expr.elements)]
                    if expr.elements and isinstance(expr.elements[0], ast.ArrayLiteral):
                        d += get_dims(expr.elements[0])
                    return d
                return []

            if v.initializer:
                dims = get_dims(v.initializer)
            elif v.type_ann.array_size is not None:
                dims = v.type_ann.fixed_sizes if v.type_ann.fixed_sizes else [v.type_ann.array_size]
            
            self._var_sizes[v.name] = dims
            self._var_types[v.name] = v.type_ann.base_type

            if v.initializer:
                owns_initializer = self._expr_allocates_heap(v.initializer)
                if isinstance(v.initializer, ast.ArrayAllocation):
                    prelude, init_expr = self._capture_expr(
                        v.initializer, class_ctx, owns_result=owns_initializer
                    )
                else:
                    prelude, init_expr = self._capture_code(
                        lambda: self._emit_array_expr(v.initializer, v.type_ann, class_ctx)
                    )
                out += prelude
                if v.type_ann.fixed_sizes:
                    dims_str = "".join(f"[{sz}]" for sz in v.type_ann.fixed_sizes)
                    out.append(f"{prefix}{base_c} {v.name}{dims_str} = {init_expr};")
                elif v.type_ann.array_size is not None and v.type_ann.array_depth == 1:
                    out.append(f"{prefix}{base_c} {v.name}[{v.type_ann.array_size}] = {init_expr};")
                else:
                    out.append(f"{prefix}{ct} {v.name} = {init_expr};")
                if self._expr_allocates_heap(v.initializer):
                    self._heap_vars.append(v.name)
            else:
                if v.type_ann.fixed_sizes:
                    dims_str = "".join(f"[{sz}]" for sz in v.type_ann.fixed_sizes)
                    out.append(f"{prefix}{base_c} {v.name}{dims_str};")
                elif v.type_ann.array_size is not None and v.type_ann.array_depth == 1:
                    out.append(f"{prefix}{base_c} {v.name}[{v.type_ann.array_size}];")
                else:
                    out.append(f"{prefix}{ct} {v.name};")
            return

        if v.initializer:
            # Check if it's a constructor call: Engine v8 = Engine("COM3")
            if v.type_ann.base_type in self._class_names:
                out.append(f"{v.type_ann.base_type} {v.name};")
                self._var_types[v.name] = v.type_ann.base_type
                if isinstance(v.initializer, ast.CallExpr):
                    call = v.initializer
                    lookup_name = f"{v.type_ann.base_type}_construct"
                    params = self._func_params.get(lookup_name, [])
                    def build_args():
                        args_parts = []
                        for i, a in enumerate(call.args):
                            param = params[i + 1] if (i + 1) < len(params) else None
                            is_ref_call = i < len(call.ref_flags) and call.ref_flags[i]
                            args_parts.append(self._emit_arg(a, param, is_ref_call, class_ctx))
                        return ", ".join(args_parts)
                    prelude, args = self._capture_code(build_args)
                    out += prelude
                    out.append(f"{v.type_ann.base_type}_construct(&{v.name}{', ' + args if args else ''});")
                    self._destructors.append((v.type_ann.base_type, v.name))
                return
            owns_initializer = self._expr_allocates_heap(v.initializer)
            prelude, init_expr = self._capture_expr(
                v.initializer, class_ctx, owns_result=owns_initializer
            )
            out += prelude
            out.append(f"{prefix}{ct} {v.name} = {init_expr};")
            self._var_types[v.name] = v.type_ann.base_type
            if self._expr_allocates_heap(v.initializer):
                self._heap_vars.append(v.name)
        else:
            if v.type_ann.is_nullable:
                out.append(f"{prefix}{ct} {v.name} = NULL;")
            else:
                out.append(f"{prefix}{ct} {v.name};")
            self._var_types[v.name] = v.type_ann.base_type

    def _emit_expr_stmt(self, stmt: ast.ExpressionStatement, out: list[str], class_ctx=None):
        expr = stmt.expr
        heap_start = len(self._heap_vars)
        if isinstance(expr, ast.CallExpr) and isinstance(expr.callee, ast.Identifier):
            if expr.callee.name == "print":
                self._emit_print(expr, out, class_ctx)
                self._emit_heap_cleanup_from(out, heap_start, pop=True)
                return

        prelude, expr_s = self._capture_expr(expr, class_ctx)
        out += prelude
        out.append(expr_s + ";")
        if not isinstance(expr, ast.AssignExpr):
            self._emit_heap_cleanup_from(out, heap_start, pop=True)

    def _get_fmt(self, oda_type: str) -> str:
        """Return printf format specifier for an Oda type."""
        if oda_type in self._enum_variants:
            return "%d"
        return _FMT.get(oda_type, "%s")

    def _infer_expr_type(self, node) -> str:
        """Best-effort type inference for printf format selection."""
        if isinstance(node, ast.IntegerLiteral):
            return "int"
        if isinstance(node, ast.UIntLiteral):
            return "uint"
        if isinstance(node, ast.FloatLiteral):
            return "float"
        if isinstance(node, (ast.StringLiteral, ast.InterpolatedString)):
            return "string"
        if isinstance(node, ast.CharLiteral):
            return "char"
        if isinstance(node, ast.BoolLiteral):
            return "bool"
        if isinstance(node, ast.Identifier):
            return self._var_types.get(node.name, "string")
        if isinstance(node, ast.MemberAccess):
            if isinstance(node.obj, ast.Identifier) and node.obj.name in self._enum_variants:
                return node.obj.name
            return self._infer_expr_type(node.obj)
        if isinstance(node, ast.BinaryExpr):
            if node.op == "+" and self._looks_like_string(node):
                return "string"
            return self._infer_expr_type(node.left)
        if isinstance(node, ast.CallExpr):
            if isinstance(node.callee, ast.Identifier):
                name = node.callee.name
                if name == "input": return "string"
                if name == "readFile": return "string"
                return self._func_return_types.get(name, "string")
        if isinstance(node, ast.IndexAccess):
            return self._infer_expr_type(node.obj)
        return "string"

    def _emit_print(self, call: ast.CallExpr, out: list[str], class_ctx=None):
        if not call.args:
            out.append('printf("\\n");')
            return
        arg = call.args[0]
        if isinstance(arg, ast.StringLiteral):
            val = arg.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            out.append(f'printf("{val}\\n");')
        elif isinstance(arg, ast.InterpolatedString):
            fmt_parts, arg_exprs = [], []
            for part in arg.parts:
                if isinstance(part, str):
                    fmt_parts.append(part.replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n"))
                else:
                    t = self._infer_expr_type(part)
                    fmt_parts.append(self._get_fmt(t))
                    prelude, part_s = self._capture_expr(part, class_ctx)
                    out += prelude
                    arg_exprs.append(part_s)
            fmt = "".join(fmt_parts)
            args_str = ", ".join(arg_exprs)
            out.append(f'printf("{fmt}\\n"{", " + args_str if args_str else ""});')
        elif isinstance(arg, ast.Identifier):
            t = self._var_types.get(arg.name, "string")
            fmt = self._get_fmt(t)
            prelude, arg_s = self._capture_expr(arg, class_ctx)
            out += prelude
            out.append(f'printf("{fmt}\\n", {arg_s});')
        elif isinstance(arg, ast.IntegerLiteral):
            out.append(f'printf("%d\\n", {arg.value});')
        elif isinstance(arg, ast.UIntLiteral):
            out.append(f'printf("%u\\n", {arg.value}u);')
        elif isinstance(arg, ast.FloatLiteral):
            out.append(f'printf("%f\\n", {arg.value});')
        else:
            t = self._infer_expr_type(arg)
            fmt = self._get_fmt(t)
            prelude, arg_s = self._capture_expr(arg, class_ctx)
            out += prelude
            out.append(f'printf("{fmt}\\n", {arg_s});')

    def _emit_if(self, stmt: ast.IfStatement, out: list[str], class_ctx=None):
        prelude, cond_s = self._capture_expr(stmt.condition, class_ctx)
        out += prelude
        out.append(f"if ({cond_s}) {{")
        body = []
        self._emit_block(stmt.body, body, class_ctx)
        out += ["    " + l for l in body]
        for cond, blk in stmt.elif_branches:
            prelude, cond_s = self._capture_expr(cond, class_ctx)
            if prelude:
                out.append("} else {")
                out += ["    " + l for l in prelude]
                out.append(f"    if ({cond_s}) {{")
                indent = "        "
            else:
                out.append(f"}} else if ({cond_s}) {{")
                indent = "    "
            body = []
            self._emit_block(blk, body, class_ctx)
            out += [indent + l for l in body]
            if prelude:
                out.append("    }")
        if stmt.else_body:
            out.append("} else {")
            body = []
            self._emit_block(stmt.else_body, body, class_ctx)
            out += ["    " + l for l in body]
        out.append("}")

    def _emit_while(self, stmt: ast.WhileStatement, out: list[str], class_ctx=None):
        prelude, cond_s = self._capture_expr(stmt.condition, class_ctx)
        out += prelude
        out.append(f"while ({cond_s}) {{")
        body = []
        self._emit_block(stmt.body, body, class_ctx)
        out += ["    " + l for l in body]
        out.append("}")

    def _emit_for(self, stmt: ast.ForStatement, out: list[str], class_ctx=None):
        init_s = ""
        if isinstance(stmt.init, ast.VarDeclaration):
            ct = self._c_type(stmt.init.type_ann)
            prelude, init_expr = self._capture_expr(stmt.init.initializer, class_ctx)
            out += prelude
            init_s = f"{ct} {stmt.init.name} = {init_expr}"
            self._var_types[stmt.init.name] = stmt.init.type_ann.base_type
        prelude, cond_s = self._capture_expr(stmt.condition, class_ctx) if stmt.condition else ([], "")
        out += prelude
        prelude, upd_s = self._capture_expr(stmt.update, class_ctx) if stmt.update else ([], "")
        out += prelude
        out.append(f"for ({init_s}; {cond_s}; {upd_s}) {{")
        body = []
        self._emit_block(stmt.body, body, class_ctx)
        out += ["    " + l for l in body]
        out.append("}")

    def _emit_for_range(self, stmt: ast.ForRangeStatement, out: list[str], class_ctx=None):
        ct = self._c_type(stmt.var_type)
        prelude, start_expr = self._capture_expr(stmt.start, class_ctx)
        out += prelude
        prelude, end_expr = self._capture_expr(stmt.end, class_ctx)
        out += prelude
        prelude, step_expr = self._capture_expr(stmt.step, class_ctx) if stmt.step else ([], "1")
        out += prelude
        self._var_types[stmt.var_name] = stmt.var_type.base_type
        
        s_tmp = self._next_temp() + "_s"
        e_tmp = self._next_temp() + "_e"
        out.append(f"{ct} {s_tmp} = {start_expr};")
        out.append(f"{ct} {e_tmp} = {end_expr};")
        
        op_inc = "<=" if stmt.is_inclusive else "<"
        op_dec = ">=" if stmt.is_inclusive else ">"

        body = []
        self._emit_block(stmt.body, body, class_ctx)
        
        out.append(f"if ({s_tmp} <= {e_tmp}) {{")
        out.append(f"    for ({ct} {stmt.var_name} = {s_tmp}; {stmt.var_name} {op_inc} {e_tmp}; {stmt.var_name} += {step_expr}) {{")
        out += ["        " + l for l in body]
        out.append("    }")
        out.append("} else {")
        out.append(f"    for ({ct} {stmt.var_name} = {s_tmp}; {stmt.var_name} {op_dec} {e_tmp}; {stmt.var_name} -= {step_expr}) {{")
        out += ["        " + l for l in body]
        out.append("    }")
        out.append("}")

    def _emit_for_in(self, stmt: ast.ForInStatement, out: list[str], class_ctx=None):
        prelude, iterable_s = self._capture_expr(stmt.iterable, class_ctx)
        out += prelude
        
        dims = None
        is_string = False
        
        if isinstance(stmt.iterable, ast.Identifier):
            dims = self._var_sizes.get(stmt.iterable.name)
            if self._var_types.get(stmt.iterable.name) == "string" and not dims:
                is_string = True
        elif isinstance(stmt.iterable, ast.IndexAccess):
            obj_name = getattr(stmt.iterable.obj, "name", None)
            if obj_name and obj_name in self._var_sizes:
                outer_dims = self._var_sizes[obj_name]
                if len(outer_dims) > 1:
                    dims = outer_dims[1:]
                    
        if not dims and self._infer_expr_type(stmt.iterable) == "string":
            is_string = True

        if is_string:
            iter_tmp = self._next_temp() + "_iter"
            out.append(f"char* {iter_tmp} = {iterable_s};")
            size_tmp = self._next_temp() + "_size"
            out.append(f"int {size_tmp} = strlen({iter_tmp});")
            idx = self._next_temp()
            prelude, step_s = self._capture_expr(stmt.step, class_ctx) if stmt.step else ([], "1")
            out += prelude
            
            if not stmt.is_reversed:
                out.append(f"for (int {idx} = 0; {idx} < {size_tmp}; {idx} += {step_s}) {{")
            else:
                out.append(f"for (int {idx} = {size_tmp} - 1; {idx} >= 0; {idx} -= {step_s}) {{")
                
            self._var_types[stmt.var_name] = stmt.var_type.base_type
            if stmt.var_type.base_type == "string":
                out.append(f"    char {stmt.var_name}_buf[2] = {{ {iter_tmp}[{idx}], '\\0' }};")
                out.append(f"    char* {stmt.var_name} = {stmt.var_name}_buf;")
            else:
                out.append(f"    {self._c_type(stmt.var_type)} {stmt.var_name} = {iter_tmp}[{idx}];")
                
            body = []
            self._emit_block(stmt.body, body, class_ctx)
            out += ["    " + l for l in body]
            out.append("}")
        elif dims and len(dims) > 0:
            size = dims[0]
            self._var_types[stmt.var_name] = stmt.var_type.base_type
            if len(dims) > 1:
                self._var_sizes[stmt.var_name] = dims[1:]
            
            idx = self._next_temp()
            prelude, step_s = self._capture_expr(stmt.step, class_ctx) if stmt.step else ([], "1")
            out += prelude
            
            if not stmt.is_reversed:
                out.append(f"for (int {idx} = 0; {idx} < {size}; {idx} += {step_s}) {{")
            else:
                out.append(f"for (int {idx} = {size} - 1; {idx} >= 0; {idx} -= {step_s}) {{")
            
            out.append(f"    {self._c_type(stmt.var_type)} {stmt.var_name} = {iterable_s}[{idx}];")
            body = []
            self._emit_block(stmt.body, body, class_ctx)
            out += ["    " + l for l in body]
            out.append("}")
        else:
            pass # Caught by semantic analysis

    def _emit_match(self, stmt: ast.MatchStatement, out: list[str], class_ctx=None):
        prelude, expr_s = self._capture_expr(stmt.expr, class_ctx)
        out += prelude
        expr_type = self._infer_expr_type(stmt.expr)
        for i, arm in enumerate(stmt.arms):
            kw = "if" if i == 0 else "} else if"
            if arm.pattern is None:
                if i > 0:
                    out.append("} else {")
                else:
                    out.append("/* default */ {")
            else:
                prelude, pat_s = self._capture_expr(arm.pattern, class_ctx)
                out += prelude
                if expr_type == "string":
                    out.append(f"{kw} (strcmp({expr_s}, {pat_s}) == 0) {{")
                else:
                    out.append(f"{kw} ({expr_s} == {pat_s}) {{")
            body = []
            self._emit_block(arm.body, body, class_ctx)
            out += ["    " + l for l in body]
        out.append("}")

    def _emit_guard(self, stmt: ast.GuardStatement, out: list[str], class_ctx=None):
        owns_expr = self._expr_allocates_heap(stmt.expr)
        prelude, expr_s = self._capture_expr(stmt.expr, class_ctx, owns_result=owns_expr)
        out += prelude
        ct = self._c_type(stmt.var_type)
        out.append(f"/* guard unwrap */")
        out.append(f"{ct} {stmt.var_name} = {expr_s};")
        if owns_expr:
            self._heap_vars.append(stmt.var_name)
        out.append(f"if ({stmt.var_name} == NULL) {{")
        for i, case in enumerate(stmt.cases):
            const_name = _ERROR_CONSTANTS.get(case.error_type, "ODA_ERROR_IO")
            prefix = "if" if i == 0 else "} else if"
            out.append(f"    {prefix} (_oda_error == {const_name}) {{")
            body = []
            self._emit_block(case.body, body, class_ctx)
            out += ["        " + l for l in body]
        out.append("    } else {")
        out.append('        fprintf(stderr, "oda: unhandled guard error\\n");')
        out.append("        exit(1);")
        out.append("    }")
        out.append("}")

    # ── expression codegen ───────────────────────────────────
    def _expr(self, node, class_ctx=None, *, owns_result: bool = False) -> str:
        if isinstance(node, ast.IntegerLiteral):
            return str(node.value)
        if isinstance(node, ast.UIntLiteral):
            return f"{node.value}u"
        if isinstance(node, ast.FloatLiteral):
            return str(node.value)
        if isinstance(node, ast.StringLiteral):
            val = node.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            return f'"{val}"'
        if isinstance(node, ast.CharLiteral):
            return f"'{node.value}'"
        if isinstance(node, ast.InterpolatedString):
            tmp = self._interp_string(node, class_ctx)
            if not owns_result:
                self._heap_vars.append(tmp)
            return tmp
        if isinstance(node, ast.BoolLiteral):
            return "1" if node.value else "0"
        if isinstance(node, ast.NullLiteral):
            return "NULL"
        if isinstance(node, ast.Identifier):
            name = node.name
            if class_ctx and name.startswith("_"):
                return f"self->{name}"
            if name in self._ref_params:
                return f"(*{name})"
            return name
        if isinstance(node, ast.ArrayLiteral):
            if not node.elements:
                return "{0}"
            
            # Check if elements are also arrays (nested)
            is_nested = any(isinstance(e, ast.ArrayLiteral) for e in node.elements)
            elems_code = []
            for e in node.elements:
                e_code = self._expr(e, class_ctx)
                if isinstance(e, ast.ArrayLiteral):
                    # We need a cast for the nested compound literal
                    # For now assume it's the same base type with depth-1
                    # This is a bit of a hack without full type info in _expr
                    elems_code.append(f"(void*){e_code}") # fallback to void* for safety in C
                else:
                    elems_code.append(e_code)
            
            elems = ", ".join(elems_code)
            return f"{{{elems}}}"
        if isinstance(node, ast.ArrayAllocation):
            depth = len(node.sizes)
            base = _C_TYPES.get(node.base_type, node.base_type)
            if depth == 1:
                size_expr = self._expr(node.sizes[0], class_ctx)
                expr_code = f"({base}*)malloc(sizeof({base}) * ({size_expr}))"
            else:
                self._emit_alloc_helper(depth)
                sizes_exprs = ", ".join(self._expr(sz, class_ctx) for sz in node.sizes)
                cast = f"({base}{'*' * depth})"
                expr_code = f"{cast}_oda_alloc_{depth}d({sizes_exprs}, sizeof({base}))"
            return self._materialize_heap_expr(node, expr_code, owns_result=owns_result)
        if isinstance(node, ast.BinaryExpr):
            l = self._expr(node.left, class_ctx)
            r = self._expr(node.right, class_ctx)
            if node.op == "+" and self._looks_like_string(node.left):
                r = self._ensure_str(node.right, r, class_ctx)
                l = self._ensure_str(node.left, l, class_ctx)
                expr_code = f"_oda_str_concat({l}, {r})"
                return self._materialize_heap_expr(node, expr_code, owns_result=owns_result)
            if node.op == "+" and self._looks_like_string(node.right):
                l = self._ensure_str(node.left, l, class_ctx)
                r = self._ensure_str(node.right, r, class_ctx)
                expr_code = f"_oda_str_concat({l}, {r})"
                return self._materialize_heap_expr(node, expr_code, owns_result=owns_result)
            if node.op == "??":
                return f"({l} != NULL ? {l} : {r})"
            return f"({l} {node.op} {r})"
        if isinstance(node, ast.UnaryExpr):
            return f"({node.op}{self._expr(node.operand, class_ctx)})"
        if isinstance(node, ast.CastExpr):
            expr_s = self._expr(node.expr, class_ctx, owns_result=owns_result)
            return f"(({self._c_type(node.target_type)})({expr_s}))"
        if isinstance(node, ast.AssignExpr):
            t = self._expr(node.target, class_ctx)
            v = self._expr(node.value, class_ctx)
            return f"{t} {node.op} {v}"
        if isinstance(node, ast.CallExpr):
            expr_code = self._emit_call_expr(node, class_ctx)
            if self._expr_allocates_heap(node):
                return self._materialize_heap_expr(node, expr_code, owns_result=owns_result)
            return expr_code
        if isinstance(node, ast.MemberAccess):
            if isinstance(node.obj, ast.Identifier) and node.obj.name in self._enum_variants:
                return f"{node.obj.name}_{node.member}"
            obj = self._expr(node.obj, class_ctx)
            if class_ctx and isinstance(node.obj, ast.Identifier) and node.obj.name == "self":
                return f"self->{node.member}"
            return f"{obj}.{node.member}"
        if isinstance(node, ast.IndexAccess):
            obj = self._expr(node.obj, class_ctx)
            idx = self._expr(node.index, class_ctx)
            return f"{obj}[{idx}]"
        return "/* ??? */"

    def _emit_arg(self, arg, param: ast.Parameter | None, is_ref_call: bool, class_ctx=None) -> str:
        arg_s = self._expr(arg, class_ctx)
        if is_ref_call:
            return f"&{arg_s}"
        if param and param.is_ref:
            ct = self._c_type(param.type_ann)
            tmp = self._next_temp() + "_arg"
            self._add_expr_prelude(f"{ct} {tmp} = {arg_s};")
            return f"&{tmp}"
        return arg_s

    def _emit_call_expr(self, call: ast.CallExpr, class_ctx=None) -> str:
        if isinstance(call.callee, ast.Identifier):
            name = call.callee.name
            if name == "input":
                return "_oda_input()"
            
            lookup_name = name
            if name in self._class_names:
                lookup_name = f"{name}_construct"
            
            is_user_func = lookup_name in self._func_params
            params = self._func_params.get(lookup_name, [])
            
            args_parts = []
            for i, a in enumerate(call.args):
                is_ref_call = i < len(call.ref_flags) and call.ref_flags[i]
                if is_user_func:
                    param = params[i] if i < len(params) else None
                    args_parts.append(self._emit_arg(a, param, is_ref_call, class_ctx))
                else:
                    if is_ref_call:
                        a_str = self._expr(a, class_ctx)
                        args_parts.append(f"&{a_str}")
                    else:
                        args_parts.append(self._expr(a, class_ctx))
            args_str = ", ".join(args_parts)

            if name == "readFile":
                return f"_oda_read_file({args_str})"

            if name in self._class_names:
                return f"{name}({args_str})"
            return f"{name}({args_str})"
        
        if isinstance(call.callee, ast.MemberAccess):
            ma = call.callee
            obj = self._expr(ma.obj, class_ctx)
            args_parts = [f"&{obj}"]
            
            for cn in self._class_names:
                lookup_name = f"{cn}_{ma.member}"
                if lookup_name in self._func_params:
                    params = self._func_params[lookup_name]
                    for i, a in enumerate(call.args):
                        is_ref_call = i < len(call.ref_flags) and call.ref_flags[i]
                        param = params[i + 1] if (i + 1) < len(params) else None
                        args_parts.append(self._emit_arg(a, param, is_ref_call, class_ctx))
                    return f"{lookup_name}({', '.join(args_parts)})"
            
            # fallback
            for i, a in enumerate(call.args):
                args_parts.append(self._expr(a, class_ctx))
            return f"/* unknown method */ {ma.member}({', '.join(args_parts)})"
        return "/* unknown call */"

    def _interp_string(self, node: ast.InterpolatedString, class_ctx=None) -> str:
        fmt_parts, arg_list = [], []
        for part in node.parts:
            if isinstance(part, str):
                fmt_parts.append(part.replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n"))
            else:
                t = self._infer_expr_type(part)
                fmt_parts.append(self._get_fmt(t))
                arg_list.append(self._expr(part, class_ctx))
        fmt = "".join(fmt_parts)
        len_tmp = self._next_temp() + "_len"
        tmp = self._next_temp()
        args_str = (", " + ", ".join(arg_list)) if arg_list else ""
        self._add_expr_prelude(f'int {len_tmp} = snprintf(NULL, 0, "{fmt}"{args_str});')
        self._add_expr_prelude(f'if ({len_tmp} < 0) {{ fprintf(stderr, "oda: string interpolation failed\\n"); exit(1); }}')
        self._add_expr_prelude(f'char* {tmp} = (char*)malloc((size_t){len_tmp} + 1);')
        self._add_expr_prelude(f'if (!{tmp}) {{ fprintf(stderr, "oda: string interpolation allocation failed\\n"); exit(1); }}')
        self._add_expr_prelude(f'snprintf({tmp}, (size_t){len_tmp} + 1, "{fmt}"{args_str});')
        return tmp

    def _looks_like_string(self, node) -> bool:
        if isinstance(node, (ast.StringLiteral, ast.InterpolatedString)):
            return True
        if isinstance(node, ast.Identifier):
            t = self._var_types.get(node.name)
            if t == "string":
                return True
        if isinstance(node, ast.BinaryExpr) and node.op == "+":
            return self._looks_like_string(node.left) or self._looks_like_string(node.right)
        return False

    def _ensure_str(self, node, code: str, class_ctx=None) -> str:
        """Wrap non-string expression in a toString conversion for C."""
        if isinstance(node, (ast.StringLiteral, ast.InterpolatedString)):
            return code
        t = self._infer_expr_type(node)
        if t == "string":
            return code
        if t in ("int", "uint", "bool"):
            return self._track_heap_temp("char*", f"_oda_int_to_str({code})")
        if t == "float":
            return self._track_heap_temp("char*", f"_oda_float_to_str({code})")
        return code

    # ── helpers ──────────────────────────────────────────────
    def _c_type(self, ta: ast.TypeAnnotation) -> str:
        base = _C_TYPES.get(ta.base_type, ta.base_type)
        if ta.is_array:
            depth = ta.array_depth if ta.array_depth > 0 else 1
            if depth > 1:
                return f"{base}" + ("*" * depth)
            if ta.array_size is not None:
                return f"{base}"  # size handled at declaration
            return f"{base}*"
        if ta.is_nullable and ta.base_type == "string":
            return "char*"
        return base

    def _param_c(self, p: ast.Parameter) -> str:
        ct = self._c_type(p.type_ann)
        if p.is_ref:
            return f"{ct}* {p.name}"
        return f"{ct} {p.name}"
