/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;



int main(void) {
    int* numbers = (int[]){10, 20, 30};
    (void)numbers;
    for (int _oda_tmp_1 = 0; _oda_tmp_1 < 3; _oda_tmp_1 += 1) {
        int n = numbers[_oda_tmp_1];
        printf("number=%d\n", n);
    }
    int** matrix = (int*[]){(int[]){1, 2}, (int[]){3, 4}};
    (void)matrix;
    printf("matrix[1][0]=%d\n", matrix[1][0]);
    for (int _oda_tmp_2 = 0; _oda_tmp_2 < 2; _oda_tmp_2 += 1) {
        int* row = matrix[_oda_tmp_2];
        printf("row-sum=%d\n", (row[0] + row[1]));
    }
    int*** cube = (int**[]){(int*[]){(int[]){1, 2}, (int[]){3, 4}}, (int*[]){(int[]){5, 6}, (int[]){7, 8}}};
    (void)cube;
    printf("cube[1][0][1]=%d\n", cube[1][0][1]);
    return 0;
}
