/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;

typedef struct {
    int _value;
} Counter;


void Counter_construct(Counter* self, int start) {
    self->_value = start;
    printf("counter opened\n");
}

void Counter_inc(Counter* self) {
    self->_value += 1;
}

int Counter_get(Counter* self) {
    return self->_value;
}

void Counter_destruct(Counter* self) {
    if ((self->_value >= 0)) {
        printf("counter closed\n");
    }
}


int main(void) {
    Counter counter;
    (void)counter;
    Counter_construct(&counter, 5);
    Counter_inc(&counter);
    int current = Counter_get(&counter);
    (void)current;
    printf("counter now=%d\n", current);
    Counter_destruct(&counter);
    return 0;
}
