/* Generated by OdaLanguage Transpiler v0.1 */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;

static ODA_UNUSED char* _oda_int_to_str(int v) {
    char* buf = (char*)malloc(24);
    snprintf(buf, 24, "%d", v);
    return buf;
}

static ODA_UNUSED char* _oda_float_to_str(double v) {
    char* buf = (char*)malloc(48);
    snprintf(buf, 48, "%g", v);
    return buf;
}

static ODA_UNUSED char* _oda_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* r = (char*)malloc(la + lb + 1);
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}

static ODA_UNUSED char* _oda_input() {
    size_t cap = 64;
    size_t len = 0;
    char* buf = (char*)malloc(cap);
    if (!buf) {
        fprintf(stderr, "oda: input allocation failed\n");
        exit(1);
    }
    int ch;
    while ((ch = fgetc(stdin)) != EOF && ch != '\n') {
        if (len + 1 >= cap) {
            size_t new_cap = cap * 2;
            char* new_buf = (char*)realloc(buf, new_cap);
            if (!new_buf) {
                free(buf);
                fprintf(stderr, "oda: input allocation failed\n");
                exit(1);
            }
            buf = new_buf;
            cap = new_cap;
        }
        buf[len++] = (char)ch;
    }
    buf[len] = '\0';
    return buf;
}

static ODA_UNUSED char* _oda_read_file(const char* path) {
    errno = 0;
    FILE* f = fopen(path, "r");
    if (!f) {
        if (errno == ENOENT || errno == ENOTDIR) {
            _oda_error = ODA_ERROR_FILE_NOT_FOUND;
        } else if (errno == EACCES || errno == EPERM) {
            _oda_error = ODA_ERROR_PERMISSION_DENIED;
        } else {
            _oda_error = ODA_ERROR_IO;
        }
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* string = (char*)malloc(fsize + 1);
    if (!string) {
        fclose(f);
        _oda_error = ODA_ERROR_IO;
        return NULL;
    }
    fread(string, fsize, 1, f);
    fclose(f);
    string[fsize] = 0;
    _oda_error = ODA_ERROR_NONE;
    return string;
}



int main(void) {
    char* command = "start";
    if (strcmp(command, "start") == 0) {
        printf("command=start\n");
    } else if (strcmp(command, "stop") == 0) {
        printf("command=stop\n");
    } else {
        printf("command=unknown\n");
    }
    int _oda_tmp_1_s = 0;
    int _oda_tmp_2_e = 3;
    if (_oda_tmp_1_s <= _oda_tmp_2_e) {
        for (int i = _oda_tmp_1_s; i < _oda_tmp_2_e; i += 1) {
            printf("range i=%d\n", i);
        }
    } else {
        for (int i = _oda_tmp_1_s; i > _oda_tmp_2_e; i -= 1) {
            printf("range i=%d\n", i);
        }
    }
    int _oda_tmp_3_s = 0;
    int _oda_tmp_4_e = 4;
    if (_oda_tmp_3_s <= _oda_tmp_4_e) {
        for (int i = _oda_tmp_3_s; i <= _oda_tmp_4_e; i += 2) {
            printf("inclusive step i=%d\n", i);
        }
    } else {
        for (int i = _oda_tmp_3_s; i >= _oda_tmp_4_e; i -= 2) {
            printf("inclusive step i=%d\n", i);
        }
    }
    int row = 0;
    while ((row < 2)) {
        int _oda_tmp_5_s = 0;
        int _oda_tmp_6_e = 2;
        if (_oda_tmp_5_s <= _oda_tmp_6_e) {
            for (int col = _oda_tmp_5_s; col < _oda_tmp_6_e; col += 1) {
                printf("cell=%d,%d\n", row, col);
            }
        } else {
            for (int col = _oda_tmp_5_s; col > _oda_tmp_6_e; col -= 1) {
                printf("cell=%d,%d\n", row, col);
            }
        }
        row += 1;
    }
    return 0;
}
