/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;



int main(void) {
    char* command = "start";
    (void)command;
    if (strcmp(command, "start") == 0) {
        printf("command=start\n");
    } else if (strcmp(command, "stop") == 0) {
        printf("command=stop\n");
    } else {
        printf("command=unknown\n");
    }
    int _oda_tmp_1_s = 0;
    int _oda_tmp_2_e = 3;
    if (_oda_tmp_1_s <= _oda_tmp_2_e) {
        for (int i = _oda_tmp_1_s; i < _oda_tmp_2_e; i += 1) {
            printf("range i=%d\n", i);
        }
    } else {
        for (int i = _oda_tmp_1_s; i > _oda_tmp_2_e; i -= 1) {
            printf("range i=%d\n", i);
        }
    }
    int _oda_tmp_3_s = 0;
    int _oda_tmp_4_e = 4;
    if (_oda_tmp_3_s <= _oda_tmp_4_e) {
        for (int i = _oda_tmp_3_s; i <= _oda_tmp_4_e; i += 2) {
            printf("inclusive step i=%d\n", i);
        }
    } else {
        for (int i = _oda_tmp_3_s; i >= _oda_tmp_4_e; i -= 2) {
            printf("inclusive step i=%d\n", i);
        }
    }
    int row = 0;
    (void)row;
    while ((row < 2)) {
        int _oda_tmp_5_s = 0;
        int _oda_tmp_6_e = 2;
        if (_oda_tmp_5_s <= _oda_tmp_6_e) {
            for (int col = _oda_tmp_5_s; col < _oda_tmp_6_e; col += 1) {
                printf("cell=%d,%d\n", row, col);
            }
        } else {
            for (int col = _oda_tmp_5_s; col > _oda_tmp_6_e; col -= 1) {
                printf("cell=%d,%d\n", row, col);
            }
        }
        row += 1;
    }
    return 0;
}
