/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;


int add(int left, int right) {
    return (left + right);
}

void bump(int* value) {
    (*value) += 1;
}


int main(void) {
    int total = add(20, 22);
    (void)total;
    printf("total=%d\n", total);
    bump(&total);
    printf("bumped=%d\n", total);
    return 0;
}
