/* Generated by OdaLanguage Transpiler v0.1 */
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;

static ODA_UNUSED char* _oda_read_file(const char* path) {
    errno = 0;
    FILE* f = fopen(path, "r");
    if (!f) {
        if (errno == ENOENT || errno == ENOTDIR) {
            _oda_error = ODA_ERROR_FILE_NOT_FOUND;
        } else if (errno == EACCES || errno == EPERM) {
            _oda_error = ODA_ERROR_PERMISSION_DENIED;
        } else {
            _oda_error = ODA_ERROR_IO;
        }
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* string = (char*)malloc(fsize + 1);
    if (!string) {
        fclose(f);
        _oda_error = ODA_ERROR_IO;
        return NULL;
    }
    fread(string, fsize, 1, f);
    fclose(f);
    string[fsize] = 0;
    _oda_error = ODA_ERROR_NONE;
    return string;
}


void show_hello_file(void) {
    /* guard unwrap */
    char* content = _oda_read_file("examples/hello.oda");
    if (content == NULL) {
        if (_oda_error == ODA_ERROR_FILE_NOT_FOUND) {
            printf("hello example is missing\n");
            free(content);
            return;
        } else {
            fprintf(stderr, "oda: unhandled guard error\n");
            exit(1);
        }
    }
    printf("loaded hello.oda\n");
    printf("%s\n", content);
    free(content);
}


int main(void) {
    show_hello_file();
    return 0;
}
