/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

static ODA_UNUSED char* _oda_int_to_str(int v) {
    char* buf = (char*)malloc(24);
    snprintf(buf, 24, "%d", v);
    return buf;
}

static ODA_UNUSED char* _oda_float_to_str(double v) {
    char* buf = (char*)malloc(48);
    snprintf(buf, 48, "%g", v);
    return buf;
}

static ODA_UNUSED char* _oda_str_concat(const char* a, const char* b) {
    size_t la = strlen(a), lb = strlen(b);
    char* r = (char*)malloc(la + lb + 1);
    memcpy(r, a, la);
    memcpy(r + la, b, lb + 1);
    return r;
}

static ODA_UNUSED char* _oda_input() {
    size_t cap = 64;
    size_t len = 0;
    char* buf = (char*)malloc(cap);
    if (!buf) {
        fprintf(stderr, "oda: input allocation failed\n");
        exit(1);
    }
    int ch;
    while ((ch = fgetc(stdin)) != EOF && ch != '\n') {
        if (len + 1 >= cap) {
            size_t new_cap = cap * 2;
            char* new_buf = (char*)realloc(buf, new_cap);
            if (!new_buf) {
                free(buf);
                fprintf(stderr, "oda: input allocation failed\n");
                exit(1);
            }
            buf = new_buf;
            cap = new_cap;
        }
        buf[len++] = (char)ch;
    }
    buf[len] = '\0';
    return buf;
}

static ODA_UNUSED char* _oda_read_file(const char* path) {
    FILE* f = fopen(path, "r");
    if (!f) return NULL;
    fseek(f, 0, SEEK_END);
    long fsize = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* string = (char*)malloc(fsize + 1);
    fread(string, fsize, 1, f);
    fclose(f);
    string[fsize] = 0;
    return string;
}


void show_hello_file(void) {
    /* guard unwrap */
    char* content = _oda_read_file("examples/hello.oda");
    if (content == NULL) {
        /* when(FileNotFound) */
        printf("hello example is missing\n");
        return;
    }
    printf("loaded hello.oda\n");
    printf("%s\n", content);
}


int main(void) {
    show_hello_file();
    return 0;
}
