/* Generated by OdaLanguage Transpiler v0.1 */
#include <stdio.h>
#include <stdlib.h>

#if defined(__GNUC__) || defined(__clang__)
#define ODA_UNUSED __attribute__((unused))
#else
#define ODA_UNUSED
#endif

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
#define ODA_THREAD_LOCAL _Thread_local
#else
#define ODA_THREAD_LOCAL
#endif

typedef enum {
    ODA_ERROR_NONE = 0,
    ODA_ERROR_FILE_NOT_FOUND,
    ODA_ERROR_PERMISSION_DENIED,
    ODA_ERROR_IO
} OdaError;

static ODA_THREAD_LOCAL ODA_UNUSED OdaError _oda_error = ODA_ERROR_NONE;



int main(void) {
    int a = 6;
    (void)a;
    int b = 7;
    (void)b;
    printf("Hello from OdaLanguage\n");
    printf("a+b= %d\n", (a + b));
    return 0;
}
