"""C code generator — translates the OdaLanguage AST into a Unity Build C file."""
from __future__ import annotations
from . import ast_nodes as ast

# C type mapping
_C_TYPES = {
    "int": "int", "uint": "unsigned int", "float": "double",
    "char": "char", "string": "char*", "bool": "int",
}

_FMT = {
    "int": "%d", "uint": "%u", "float": "%f",
    "char": "%c", "string": "%s", "bool": "%d",
}


class CCodeGenerator:
    def __init__(self):
        self.indent = 0
        self._top: list[str] = []        # structs, prototypes
        self._funcs: list[str] = []      # function definitions
        self._main: list[str] = []       # top-level → main()
        self._helpers_emitted: set[str] = set()
        self._class_names: set[str] = set()
        self._destructors: list[tuple[str, str]] = []  # (class, varname)
        self._temp_counter = 0
        self._var_types: dict[str, str] = {}  # variable name → oda type
        self._var_sizes: dict[str, list[int]] = {}  # dimensions for arrays
        self._func_params: dict[str, list[ast.Parameter]] = {}  # func name → param list
        self._func_return_types: dict[str, str] = {}  # func name → return oda type
        self._ref_params: set[str] = set()  # currently active ref param names

    # ── public API ───────────────────────────────────────────
    def generate(self, program: ast.Program) -> str:
        # Discover classes and functions first
        for s in program.statements:
            if isinstance(s, ast.ClassDeclaration):
                self._class_names.add(s.name)
                if s.constructor:
                    self._func_params[f"{s.name}_construct"] = s.constructor.params
                for m in s.methods:
                    self._func_params[f"{s.name}_{m.name}"] = m.params
            elif isinstance(s, ast.FuncDeclaration):
                self._func_params[s.name] = s.params
                if s.return_type:
                    self._func_return_types[s.name] = s.return_type.base_type

        for s in program.statements:
            self._emit_toplevel(s)

        return self._assemble()

    # ── assembly ─────────────────────────────────────────────
    def _assemble(self) -> str:
        lines = [
            "/* Generated by OdaLanguage Transpiler v0.1 */",
            "#include <stdio.h>",
            "#include <stdlib.h>",
            "#include <string.h>",
            "",
        ]
        if "_oda_str_concat" not in self._helpers_emitted:
            self._emit_str_helper()
        lines += self._top
        lines.append("")
        lines += self._funcs
        lines.append("")
        lines.append("int main(void) {")
        lines += ["    " + l for l in self._main]
        # RAII: inject destructors
        for cls, var in reversed(self._destructors):
            lines.append(f"    {cls}_destruct(&{var});")
        lines.append("    return 0;")
        lines.append("}")
        lines.append("")
        return "\n".join(lines)

    def _emit_str_helper(self):
        self._helpers_emitted.add("_oda_str_concat")
        self._top += [
            "static char* _oda_int_to_str(int v) {",
            "    char* buf = (char*)malloc(24);",
            "    snprintf(buf, 24, \"%d\", v);",
            "    return buf;",
            "}",
            "",
            "static char* _oda_float_to_str(double v) {",
            "    char* buf = (char*)malloc(48);",
            "    snprintf(buf, 48, \"%g\", v);",
            "    return buf;",
            "}",
            "",
            "static char* _oda_str_concat(const char* a, const char* b) {",
            "    size_t la = strlen(a), lb = strlen(b);",
            "    char* r = (char*)malloc(la + lb + 1);",
            "    memcpy(r, a, la);",
            "    memcpy(r + la, b, lb + 1);",
            "    return r;",
            "}",
            "",
            "static char* _oda_input() {",
            "    char* buf = (char*)malloc(1024);",
            "    if (fgets(buf, 1024, stdin) != NULL) {",
            "        size_t len = strlen(buf);",
            "        if (len > 0 && buf[len-1] == '\\n') buf[len-1] = '\\0';",
            "    }",
            "    return buf;",
            "}",
            "",
            "static char* _oda_read_file(const char* path) {",
            "    FILE* f = fopen(path, \"r\");",
            "    if (!f) return NULL;",
            "    fseek(f, 0, SEEK_END);",
            "    long fsize = ftell(f);",
            "    fseek(f, 0, SEEK_SET);",
            "    char* string = (char*)malloc(fsize + 1);",
            "    fread(string, fsize, 1, f);",
            "    fclose(f);",
            "    string[fsize] = 0;",
            "    return string;",
            "}",
            "",
        ]

    def _next_temp(self) -> str:
        self._temp_counter += 1
        return f"_oda_tmp_{self._temp_counter}"

    # ── top-level dispatch ───────────────────────────────────
    def _emit_toplevel(self, stmt):
        if isinstance(stmt, ast.ClassDeclaration):
            self._emit_class(stmt)
        elif isinstance(stmt, ast.FuncDeclaration):
            self._emit_func_def(stmt)
        elif isinstance(stmt, ast.ImportStatement):
            self._top.append(f"/* import {stmt.module_path} */")
        else:
            # Top-level code goes into main()
            self._emit_stmt(stmt, self._main)

    # ── class → struct + functions ───────────────────────────
    def _emit_class(self, cls: ast.ClassDeclaration):
        self._top.append(f"typedef struct {{")
        for f in cls.fields:
            ct = self._c_type(f.type_ann)
            self._top.append(f"    {ct} {f.name};")
        self._top.append(f"}} {cls.name};")
        self._top.append("")

        # Constructor
        if cls.constructor:
            params = ", ".join(
                [f"{cls.name}* self"] +
                [f"{self._c_type(p.type_ann)} {p.name}" for p in cls.constructor.params]
            )
            self._funcs.append(f"void {cls.name}_construct({params}) {{")
            body_lines: list[str] = []
            old_refs = self._ref_params
            self._ref_params = {p.name for p in cls.constructor.params}
            self._emit_block(cls.constructor.body, body_lines, cls.name)
            self._ref_params = old_refs
            self._funcs += ["    " + l for l in body_lines]
            self._funcs.append("}")
            self._funcs.append("")

        # Methods
        for m in cls.methods:
            params = ", ".join(
                [f"{cls.name}* self"] +
                [self._param_c(p) for p in m.params]
            )
            ret = "void"
            if m.return_type:
                ret = self._c_type(m.return_type)
            self._funcs.append(f"{ret} {cls.name}_{m.name}({params}) {{")
            body_lines = []
            old_refs = self._ref_params
            self._ref_params = {p.name for p in m.params}
            self._emit_block(m.body, body_lines, cls.name)
            self._ref_params = old_refs
            self._funcs += ["    " + l for l in body_lines]
            self._funcs.append("}")
            self._funcs.append("")

        # Destructor
        if cls.destructor:
            self._funcs.append(f"void {cls.name}_destruct({cls.name}* self) {{")
            body_lines = []
            self._emit_block(cls.destructor.body, body_lines, cls.name)
            self._funcs += ["    " + l for l in body_lines]
            self._funcs.append("}")
            self._funcs.append("")

    # ── function definition ──────────────────────────────────
    def _emit_func_def(self, func: ast.FuncDeclaration):
        self._func_params[func.name] = func.params
        if func.return_type:
            self._func_return_types[func.name] = func.return_type.base_type
        params = ", ".join(self._param_c(p) for p in func.params)
        if not params:
            params = "void"
        ret = "void"
        if func.return_type:
            ret = self._c_type(func.return_type)
        self._funcs.append(f"{ret} {func.name}({params}) {{")
        # All params are passed as pointers to generalize ref support
        old_refs = self._ref_params
        self._ref_params = {p.name for p in func.params}
        for p in func.params:
            self._var_types[p.name] = p.type_ann.base_type
        body_lines: list[str] = []
        self._emit_block(func.body, body_lines)
        self._funcs += ["    " + l for l in body_lines]
        self._funcs.append("}")
        self._funcs.append("")
        self._ref_params = old_refs

    # ── statements ───────────────────────────────────────────
    def _emit_stmt(self, stmt, out: list[str], class_ctx: str | None = None):
        if isinstance(stmt, ast.VarDeclaration):
            self._emit_var_decl(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ExpressionStatement):
            self._emit_expr_stmt(stmt, out, class_ctx)
        elif isinstance(stmt, ast.IfStatement):
            self._emit_if(stmt, out, class_ctx)
        elif isinstance(stmt, ast.WhileStatement):
            self._emit_while(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ForStatement):
            self._emit_for(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ForRangeStatement):
            self._emit_for_range(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ForInStatement):
            self._emit_for_in(stmt, out, class_ctx)
        elif isinstance(stmt, ast.ReturnStatement):
            if stmt.value:
                out.append(f"return {self._expr(stmt.value, class_ctx)};")
            else:
                out.append("return;")
        elif isinstance(stmt, ast.BreakStatement):
            out.append("break;")
        elif isinstance(stmt, ast.ContinueStatement):
            out.append("continue;")
        elif isinstance(stmt, ast.MatchStatement):
            self._emit_match(stmt, out, class_ctx)
        elif isinstance(stmt, ast.GuardStatement):
            self._emit_guard(stmt, out, class_ctx)

    def _emit_block(self, stmts: list, out: list[str], class_ctx: str | None = None):
        for s in stmts:
            self._emit_stmt(s, out, class_ctx)

    def _emit_array_expr(self, node, ta: ast.TypeAnnotation, class_ctx=None) -> str:
        if isinstance(node, ast.ArrayLiteral):
            base = _C_TYPES.get(ta.base_type, ta.base_type)
            depth = ta.array_depth
            elems = []
            for e in node.elements:
                if isinstance(e, ast.ArrayLiteral):
                    # nested
                    inner_ta = ast.TypeAnnotation(base_type=ta.base_type, is_array=True, array_depth=depth-1)
                    elems.append(self._emit_array_expr(e, inner_ta, class_ctx))
                else:
                    elems.append(self._expr(e, class_ctx))
            
            stars = "*" * (depth - 1)
            cast = f"({base}{stars}[])" if depth > 0 else ""
            return f"{cast}{{{', '.join(elems)}}}"
        return self._expr(node, class_ctx)

    def _emit_var_decl(self, v: ast.VarDeclaration, out: list[str], class_ctx=None):
        ct = self._c_type(v.type_ann)
        prefix = "const " if v.is_immutable else ""
        base_c = _C_TYPES.get(v.type_ann.base_type, v.type_ann.base_type)

        if v.type_ann.is_array:
            dims = []
            def get_dims(expr):
                if isinstance(expr, ast.ArrayLiteral):
                    d = [len(expr.elements)]
                    if expr.elements and isinstance(expr.elements[0], ast.ArrayLiteral):
                        d += get_dims(expr.elements[0])
                    return d
                return []

            if v.initializer:
                dims = get_dims(v.initializer)
            elif v.type_ann.array_size is not None:
                dims = v.type_ann.fixed_sizes if v.type_ann.fixed_sizes else [v.type_ann.array_size]
            
            self._var_sizes[v.name] = dims
            self._var_types[v.name] = v.type_ann.base_type

            if v.initializer:
                init_expr = self._emit_array_expr(v.initializer, v.type_ann, class_ctx)
                if v.type_ann.array_size is not None and v.type_ann.array_depth == 1:
                    out.append(f"{prefix}{base_c} {v.name}[{v.type_ann.array_size}] = {init_expr};")
                else:
                    out.append(f"{prefix}{ct} {v.name} = {init_expr};")
            else:
                if v.type_ann.array_size is not None and v.type_ann.array_depth == 1:
                    out.append(f"{prefix}{base_c} {v.name}[{v.type_ann.array_size}];")
                else:
                    out.append(f"{prefix}{ct} {v.name};")
            return

        if v.initializer:
            init_expr = self._expr(v.initializer, class_ctx)
            # Check if it's a constructor call: Engine v8 = Engine("COM3")
            if v.type_ann.base_type in self._class_names:
                out.append(f"{v.type_ann.base_type} {v.name};")
                self._var_types[v.name] = v.type_ann.base_type
                # Extract args from the constructor call
                if isinstance(v.initializer, ast.CallExpr):
                    args = ", ".join(self._expr(a, class_ctx) for a in v.initializer.args)
                    out.append(f"{v.type_ann.base_type}_construct(&{v.name}{', ' + args if args else ''});")
                    self._destructors.append((v.type_ann.base_type, v.name))
                return
            out.append(f"{prefix}{ct} {v.name} = {init_expr};")
            self._var_types[v.name] = v.type_ann.base_type
        else:
            if v.type_ann.is_nullable:
                out.append(f"{prefix}{ct} {v.name} = NULL;")
            else:
                out.append(f"{prefix}{ct} {v.name};")
            self._var_types[v.name] = v.type_ann.base_type

    def _emit_expr_stmt(self, stmt: ast.ExpressionStatement, out: list[str], class_ctx=None):
        expr = stmt.expr
        if isinstance(expr, ast.CallExpr) and isinstance(expr.callee, ast.Identifier):
            if expr.callee.name == "print":
                self._emit_print(expr, out, class_ctx)
                return
        if isinstance(expr, ast.CallExpr) and isinstance(expr.callee, ast.MemberAccess):
            # obj.method(args) → ClassName_method(&obj, args)
            ma = expr.callee
            obj_name = self._expr(ma.obj, class_ctx)
            args_parts = []
            for i, a in enumerate(expr.args):
                a_str = self._expr(a, class_ctx)
                if i < len(expr.ref_flags) and expr.ref_flags[i]:
                    args_parts.append(f"&{a_str}")
                else:
                    args_parts.append(a_str)
            args_str = ", ".join(args_parts)
            # We need to find the class name — for now use a simple heuristic
            out.append(f"/* {obj_name}.{ma.member}() */")
            # Try to find class type from variable name pattern
            for cls_name in self._class_names:
                out.append(f"{cls_name}_{ma.member}(&{obj_name}{', ' + args_str if args_str else ''});")
                break
            else:
                out.append(f"{obj_name}.{ma.member}({args_str});")
            return

        line = self._expr(expr, class_ctx) + ";"
        out.append(line)

    def _get_fmt(self, oda_type: str) -> str:
        """Return printf format specifier for an Oda type."""
        return _FMT.get(oda_type, "%s")

    def _infer_expr_type(self, node) -> str:
        """Best-effort type inference for printf format selection."""
        if isinstance(node, ast.IntegerLiteral):
            return "int"
        if isinstance(node, ast.FloatLiteral):
            return "float"
        if isinstance(node, (ast.StringLiteral, ast.InterpolatedString)):
            return "string"
        if isinstance(node, ast.BoolLiteral):
            return "bool"
        if isinstance(node, ast.Identifier):
            return self._var_types.get(node.name, "string")
        if isinstance(node, ast.BinaryExpr):
            if node.op == "+" and self._looks_like_string(node.left):
                return "string"
            return self._infer_expr_type(node.left)
        if isinstance(node, ast.CallExpr):
            if isinstance(node.callee, ast.Identifier):
                name = node.callee.name
                if name == "input": return "string"
                if name == "readFile": return "string"
                return self._func_return_types.get(name, "string")
        if isinstance(node, ast.IndexAccess):
            return self._infer_expr_type(node.obj)
        return "string"

    def _emit_print(self, call: ast.CallExpr, out: list[str], class_ctx=None):
        if not call.args:
            out.append('printf("\\n");')
            return
        arg = call.args[0]
        if isinstance(arg, ast.StringLiteral):
            val = arg.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            out.append(f'printf("{val}\\n");')
        elif isinstance(arg, ast.InterpolatedString):
            fmt_parts, arg_exprs = [], []
            for part in arg.parts:
                if isinstance(part, str):
                    fmt_parts.append(part.replace("%", "%%").replace("\\", "\\\\").replace('"', '\\"'))
                elif isinstance(part, ast.Identifier):
                    t = self._var_types.get(part.name, "string")
                    fmt_parts.append(self._get_fmt(t))
                    arg_exprs.append(self._expr(part, class_ctx))
            fmt = "".join(fmt_parts)
            args_str = ", ".join(arg_exprs)
            out.append(f'printf("{fmt}\\n"{", " + args_str if args_str else ""});')
        elif isinstance(arg, ast.Identifier):
            t = self._var_types.get(arg.name, "string")
            fmt = self._get_fmt(t)
            out.append(f'printf("{fmt}\\n", {self._expr(arg, class_ctx)});')
        elif isinstance(arg, ast.IntegerLiteral):
            out.append(f'printf("%d\\n", {arg.value});')
        elif isinstance(arg, ast.FloatLiteral):
            out.append(f'printf("%f\\n", {arg.value});')
        else:
            t = self._infer_expr_type(arg)
            fmt = self._get_fmt(t)
            out.append(f'printf("{fmt}\\n", {self._expr(arg, class_ctx)});')

    def _emit_if(self, stmt: ast.IfStatement, out: list[str], class_ctx=None):
        out.append(f"if ({self._expr(stmt.condition, class_ctx)}) {{")
        body = []
        self._emit_block(stmt.body, body, class_ctx)
        out += ["    " + l for l in body]
        for cond, blk in stmt.elif_branches:
            out.append(f"}} else if ({self._expr(cond, class_ctx)}) {{")
            body = []
            self._emit_block(blk, body, class_ctx)
            out += ["    " + l for l in body]
        if stmt.else_body:
            out.append("} else {")
            body = []
            self._emit_block(stmt.else_body, body, class_ctx)
            out += ["    " + l for l in body]
        out.append("}")

    def _emit_while(self, stmt: ast.WhileStatement, out: list[str], class_ctx=None):
        out.append(f"while ({self._expr(stmt.condition, class_ctx)}) {{")
        body = []
        self._emit_block(stmt.body, body, class_ctx)
        out += ["    " + l for l in body]
        out.append("}")

    def _emit_for(self, stmt: ast.ForStatement, out: list[str], class_ctx=None):
        init_s = ""
        if isinstance(stmt.init, ast.VarDeclaration):
            ct = self._c_type(stmt.init.type_ann)
            init_s = f"{ct} {stmt.init.name} = {self._expr(stmt.init.initializer, class_ctx)}"
            self._var_types[stmt.init.name] = stmt.init.type_ann.base_type
        cond_s = self._expr(stmt.condition, class_ctx) if stmt.condition else ""
        upd_s = self._expr(stmt.update, class_ctx) if stmt.update else ""
        out.append(f"for ({init_s}; {cond_s}; {upd_s}) {{")
        body = []
        self._emit_block(stmt.body, body, class_ctx)
        out += ["    " + l for l in body]
        out.append("}")

    def _emit_for_range(self, stmt: ast.ForRangeStatement, out: list[str], class_ctx=None):
        ct = self._c_type(stmt.var_type)
        start_expr = self._expr(stmt.start, class_ctx)
        end_expr = self._expr(stmt.end, class_ctx)
        step_expr = self._expr(stmt.step, class_ctx) if stmt.step else "1"
        self._var_types[stmt.var_name] = stmt.var_type.base_type
        
        s_tmp = self._next_temp() + "_s"
        e_tmp = self._next_temp() + "_e"
        out.append(f"{ct} {s_tmp} = {start_expr};")
        out.append(f"{ct} {e_tmp} = {end_expr};")
        
        op_inc = "<=" if stmt.is_inclusive else "<"
        op_dec = ">=" if stmt.is_inclusive else ">"
        
        out.append(f"if ({s_tmp} <= {e_tmp}) {{")
        out.append(f"    for ({ct} {stmt.var_name} = {s_tmp}; {stmt.var_name} {op_inc} {e_tmp}; {stmt.var_name} += {step_expr}) {{")
        body_inc = []
        self._emit_block(stmt.body, body_inc, class_ctx)
        out += ["        " + l for l in body_inc]
        out.append("    }")
        out.append("} else {")
        out.append(f"    for ({ct} {stmt.var_name} = {s_tmp}; {stmt.var_name} {op_dec} {e_tmp}; {stmt.var_name} -= {step_expr}) {{")
        body_dec = []
        self._emit_block(stmt.body, body_dec, class_ctx)
        out += ["        " + l for l in body_dec]
        out.append("    }")
        out.append("}")

    def _emit_for_in(self, stmt: ast.ForInStatement, out: list[str], class_ctx=None):
        iterable_s = self._expr(stmt.iterable, class_ctx)
        dims = None
        if isinstance(stmt.iterable, ast.Identifier):
            dims = self._var_sizes.get(stmt.iterable.name)
        elif isinstance(stmt.iterable, ast.IndexAccess):
            # Simple heuristic for nested access
            obj_name = getattr(stmt.iterable.obj, "name", None)
            if obj_name and obj_name in self._var_sizes:
                outer_dims = self._var_sizes[obj_name]
                if len(outer_dims) > 1:
                    dims = outer_dims[1:]

        if dims and len(dims) > 0:
            size = dims[0]
            self._var_types[stmt.var_name] = stmt.var_type.base_type
            if len(dims) > 1:
                self._var_sizes[stmt.var_name] = dims[1:]
            
            idx = self._next_temp()
            step_s = self._expr(stmt.step, class_ctx) if stmt.step else "1"
            
            if not stmt.is_reversed:
                out.append(f"for (int {idx} = 0; {idx} < {size}; {idx} += {step_s}) {{")
            else:
                out.append(f"for (int {idx} = {size} - 1; {idx} >= 0; {idx} -= {step_s}) {{")
            
            out.append(f"    {self._c_type(stmt.var_type)} {stmt.var_name} = {iterable_s}[{idx}];")
            body = []
            self._emit_block(stmt.body, body, class_ctx)
            out += ["    " + l for l in body]
            out.append("}")
        else:
            # Fallback for unknown size
            out.append(f"/* ERROR: for-in on unknown collection size: {iterable_s} */")
            out.append(f"for (int _i = 0; _i < 0; _i++) {{ }}")

    def _emit_match(self, stmt: ast.MatchStatement, out: list[str], class_ctx=None):
        expr_s = self._expr(stmt.expr, class_ctx)
        for i, arm in enumerate(stmt.arms):
            kw = "if" if i == 0 else "} else if"
            if arm.pattern is None:
                if i > 0:
                    out.append("} else {")
                else:
                    out.append("/* default */ {")
            else:
                out.append(f"{kw} ({expr_s} == {self._expr(arm.pattern, class_ctx)}) {{")
            body = []
            self._emit_block(arm.body, body, class_ctx)
            out += ["    " + l for l in body]
        out.append("}")

    def _emit_guard(self, stmt: ast.GuardStatement, out: list[str], class_ctx=None):
        expr_s = self._expr(stmt.expr, class_ctx)
        ct = self._c_type(stmt.var_type)
        out.append(f"/* guard unwrap */")
        out.append(f"if ({expr_s} == NULL) {{")
        body = []
        for case in stmt.cases:
            body.append(f"/* err({case.error_type}) */")
            self._emit_block(case.body, body, class_ctx)
        out += ["    " + l for l in body]
        out.append("}")
        out.append(f"{ct} {stmt.var_name} = {expr_s};")

    # ── expression codegen ───────────────────────────────────
    def _expr(self, node, class_ctx=None) -> str:
        if isinstance(node, ast.IntegerLiteral):
            return str(node.value)
        if isinstance(node, ast.FloatLiteral):
            return str(node.value)
        if isinstance(node, ast.StringLiteral):
            val = node.value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
            return f'"{val}"'
        if isinstance(node, ast.InterpolatedString):
            return self._interp_string(node, class_ctx)
        if isinstance(node, ast.BoolLiteral):
            return "1" if node.value else "0"
        if isinstance(node, ast.NullLiteral):
            return "NULL"
        if isinstance(node, ast.Identifier):
            name = node.name
            if class_ctx and name.startswith("_"):
                return f"self->{name}"
            if name in self._ref_params:
                return f"(*{name})"
            return name
        if isinstance(node, ast.ArrayLiteral):
            if not node.elements:
                return "{0}"
            
            # Check if elements are also arrays (nested)
            is_nested = any(isinstance(e, ast.ArrayLiteral) for e in node.elements)
            elems_code = []
            for e in node.elements:
                e_code = self._expr(e, class_ctx)
                if isinstance(e, ast.ArrayLiteral):
                    # We need a cast for the nested compound literal
                    # For now assume it's the same base type with depth-1
                    # This is a bit of a hack without full type info in _expr
                    elems_code.append(f"(void*){e_code}") # fallback to void* for safety in C
                else:
                    elems_code.append(e_code)
            
            elems = ", ".join(elems_code)
            return f"{{{elems}}}"
        if isinstance(node, ast.BinaryExpr):
            l = self._expr(node.left, class_ctx)
            r = self._expr(node.right, class_ctx)
            if node.op == "+" and self._looks_like_string(node.left):
                r = self._ensure_str(node.right, r, class_ctx)
                l = self._ensure_str(node.left, l, class_ctx)
                return f"_oda_str_concat({l}, {r})"
            if node.op == "+" and self._looks_like_string(node.right):
                l = self._ensure_str(node.left, l, class_ctx)
                r = self._ensure_str(node.right, r, class_ctx)
                return f"_oda_str_concat({l}, {r})"
            if node.op == "??":
                return f"({l} != NULL ? {l} : {r})"
            return f"({l} {node.op} {r})"
        if isinstance(node, ast.UnaryExpr):
            return f"({node.op}{self._expr(node.operand, class_ctx)})"
        if isinstance(node, ast.AssignExpr):
            t = self._expr(node.target, class_ctx)
            v = self._expr(node.value, class_ctx)
            return f"{t} {node.op} {v}"
        if isinstance(node, ast.CallExpr):
            return self._emit_call_expr(node, class_ctx)
        if isinstance(node, ast.MemberAccess):
            obj = self._expr(node.obj, class_ctx)
            if class_ctx:
                return f"self->{node.member}"
            return f"{obj}.{node.member}"
        if isinstance(node, ast.IndexAccess):
            obj = self._expr(node.obj, class_ctx)
            idx = self._expr(node.index, class_ctx)
            return f"{obj}[{idx}]"
        return "/* ??? */"

    def _emit_call_expr(self, call: ast.CallExpr, class_ctx=None) -> str:
        if isinstance(call.callee, ast.Identifier):
            name = call.callee.name
            if name == "input":
                return "_oda_input()"
            
            lookup_name = name
            if name in self._class_names:
                lookup_name = f"{name}_construct"
            
            is_user_func = lookup_name in self._func_params
            params = self._func_params.get(lookup_name, [])
            
            args_parts = []
            for i, a in enumerate(call.args):
                a_str = self._expr(a, class_ctx)
                is_ref_call = i < len(call.ref_flags) and call.ref_flags[i]
                
                if is_user_func:
                    if is_ref_call:
                        args_parts.append(f"&{a_str}")
                    else:
                        ct = "void*"
                        if i < len(params):
                            ct = self._c_type(params[i].type_ann)
                        args_parts.append(f"&({ct}){{{a_str}}}")
                else:
                    if is_ref_call:
                        args_parts.append(f"&{a_str}")
                    else:
                        args_parts.append(a_str)
            args_str = ", ".join(args_parts)

            if name == "readFile":
                return f"_oda_read_file({args_str})"

            if name in self._class_names:
                return f"{name}({args_str})"
            return f"{name}({args_str})"
        
        if isinstance(call.callee, ast.MemberAccess):
            ma = call.callee
            obj = self._expr(ma.obj, class_ctx)
            args_parts = [f"&{obj}"]
            
            for cn in self._class_names:
                lookup_name = f"{cn}_{ma.member}"
                if lookup_name in self._func_params:
                    params = self._func_params[lookup_name]
                    for i, a in enumerate(call.args):
                        a_str = self._expr(a, class_ctx)
                        is_ref_call = i < len(call.ref_flags) and call.ref_flags[i]
                        if is_ref_call:
                            args_parts.append(f"&{a_str}")
                        else:
                            ct = "void*"
                            if i < len(params):
                                ct = self._c_type(params[i].type_ann)
                            args_parts.append(f"&({ct}){{{a_str}}}")
                    return f"{lookup_name}({', '.join(args_parts)})"
            
            # fallback
            for i, a in enumerate(call.args):
                args_parts.append(self._expr(a, class_ctx))
            return f"/* unknown method */ {ma.member}({', '.join(args_parts)})"
        return "/* unknown call */"

    def _interp_string(self, node: ast.InterpolatedString, class_ctx=None) -> str:
        """Build a sprintf call for interpolated strings."""
        fmt_parts, arg_list = [], []
        for part in node.parts:
            if isinstance(part, str):
                fmt_parts.append(part.replace("%", "%%"))
            elif isinstance(part, ast.Identifier):
                fmt_parts.append("%s")
                arg_list.append(self._expr(part, class_ctx))
        fmt = "".join(fmt_parts).replace("\\", "\\\\").replace('"', '\\"')
        tmp = self._next_temp()
        # We return the temp; caller must emit the buffer decl
        args = ", ".join(arg_list)
        return f'/* interp */ ({tmp})'  # simplified for MVP

    def _looks_like_string(self, node) -> bool:
        if isinstance(node, (ast.StringLiteral, ast.InterpolatedString)):
            return True
        if isinstance(node, ast.Identifier):
            t = self._var_types.get(node.name)
            if t == "string":
                return True
        if isinstance(node, ast.BinaryExpr) and node.op == "+":
            return self._looks_like_string(node.left) or self._looks_like_string(node.right)
        return False

    def _ensure_str(self, node, code: str, class_ctx=None) -> str:
        """Wrap non-string expression in a toString conversion for C."""
        if isinstance(node, (ast.StringLiteral, ast.InterpolatedString)):
            return code
        t = self._infer_expr_type(node)
        if t == "string":
            return code
        if t in ("int", "uint", "bool"):
            return f"_oda_int_to_str({code})"
        if t == "float":
            return f"_oda_float_to_str({code})"
        return code

    # ── helpers ──────────────────────────────────────────────
    def _c_type(self, ta: ast.TypeAnnotation) -> str:
        base = _C_TYPES.get(ta.base_type, ta.base_type)
        if ta.is_array:
            depth = ta.array_depth if ta.array_depth > 0 else 1
            if depth > 1:
                return f"{base}" + ("*" * depth)
            if ta.array_size is not None:
                return f"{base}"  # size handled at declaration
            return f"{base}*"
        if ta.is_nullable and ta.base_type == "string":
            return "char*"
        return base

    def _param_c(self, p: ast.Parameter) -> str:
        ct = self._c_type(p.type_ann)
        # ALL parameters are now pointers to generalize ref passing!
        return f"{ct}* {p.name}"
